---
title: "Mutually inclusive mechanisms of drought-induced tree mortality"
subtitle: "Code repository for Hajek, Link et al. (2022)" 
output: 
    github_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Description
The present repository is part of **Hajek, Link et al. (2022)** and contains the code necessary for preparing the dataset and fitting the hierarchical Bayesian model described in the paper.

The paper was published under an CC BY 4.0 open-access license and can be cited as follows: 

**Hajek P, Link RM, Nock CA, Bauhus J, Gebauer T, Gessler A, Kovach K, Messier C, Paquette A, Saurer M, Scherer-Lorenzen M, Rose L, Schuldt B (2022).** Mutually inclusive mechanisms of drought-induced tree mortality. _Global Change Biology_ 28(10): 3365-3378. [doi:10.1111/gcb.16146](https://doi.org/10.1111/gcb.16146)

The raw data are also available as a repository on datadryad.org: [doi:10.5061/dryad.sqv9s4n5t](https://www.doi.org/10.5061/dryad.sqv9s4n5t)

## Structure
The documents in the root folder (`/`) perform the basic steps of the data analysis.
The raw data are in the `/data` folder, the `/stan` folder contains the Stan code required for
model fitting, and intermediate results and model output are stored in `/output`.
Visual output is stored in `/figures` (folder is created locally in script 06).

``` 
/           top-level scripts:
              01_vulnerability_curves.R
              02_hydraulic_safety_margins.R
              03_impute_plot_margin_heights.R
              04_compute_neighbourhood_matrices.R
              05_stan_model_fitting.R
              06_plot_model_output.R           
/data       dataset used for model fitting
/figures    visual output
/output     saved model objects, model output etc.
/stan       model code for the Stan model
```